#!/bin/bash 
# make temp file descriptor at 4 for old error
#copy stderr and direct one copy to the log file
exec 4>&2 2> >(tee /tmp/elog)
# make temp file descriptor at 3 for old out
#copy stdout and direct one copy to the log file
exec 3>&1 1> >(tee /tmp/olog)

ls
ls ed

#restore out/err
exec 1>&3 3>&-
exec 2>&4 4>&-
ls
ls r
